networks:
  db:

volumes:
  db:

services:
  backend:
    build: backend/
    ports:
      - '8080:8080'
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=user123
      - DB_USER=user
      - DB_NAME=app
      - DB_HOST=db
  db:
    build: db/
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user123
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d app']
      interval: 3s
      timeout: 5s
      retries: 5
