networks:
  api:
  user:
  elearning:

services:
  user:
    build: user/
    networks:
      - api
      - user
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=user123
      - DB_USER=user
      - DB_NAME=app
      - DB_HOST=user-db
  user-db:
    build: user-db/
    networks:
      - user
    environment:
      - POSTGRES_PASSWORD=user123
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d app']
      interval: 3s
      timeout: 5s
      retries: 5
  elearning:
    build: elearning/
    networks:
      - api
      - elearning
    depends_on:
      elearning-db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=user123
      - DB_USER=user
      - DB_NAME=app
      - DB_HOST=elearning-db
      - USER_SERVICE_URL=http://user:8080/elearning-user
      - FAKE_DATE=true
  elearning-db:
    build: elearning-db/
    networks:
      - elearning
    environment:
      - POSTGRES_PASSWORD=user123
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d app']
      interval: 3s
      timeout: 5s
      retries: 5
  test:
    build: tests/
    profiles: [test]
    networks:
      - api
    environment:
      - USER_SERVICE_URL=http://user:8080/elearning-user
      - ELEARNING_SERVICE_URL=http://elearning:8080/elearning
  queue:
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes
    networks:
      - elearning
    environment:
      - 'AMQ_USER=admin'
      - 'AMQ_PASSWORD=admin'
      - 'AMQ_DATA_DIR=/home/jboss/data'
