networks:
  api:
  user:

volumes:
  user-db:

services:
  user:
    build: user/
    networks:
      - api
      - user
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - DB_PASSWORD=user123
      - DB_USER=user
      - DB_NAME=app
      - DB_HOST=db
  user-db:
    build: user-db/
    networks:
      - user
    volumes:
      - user-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user123
      - POSTGRES_USER=user
      - POSTGRES_DB=app
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d app']
      interval: 3s
      timeout: 5s
      retries: 5
